@extends('layout.main')

@section('title')
Eula
@endsection

@section('css')
<link rel="stylesheet" href="{{asset('')}}css/about.css">
@endsection

@section('content')
<section class="eula-section">
    <div class="container p-5">
        <h4 class="text-center fw-bold">DECLARATION</h4>
        <h6 class="text-center fw-bold">End User License Agreement</h6><br>
        <b>License</b><br>
        <p>As per the agreement Wexprez grants you the non-transferable and non-exclusive license to us the app for your
            personal use and copy for the purpose of downloading, installing
            and executing the app for which you are authorized by the download site of the App on a mobile device that
            you own and control the use of.
            <br><br>
            <b>Restrictions</b><br>
            The rights that Wexprez granted to you in this Agreement are subject to the following restrictions:
            <br><br>
            a) You are not permitted to access any App in order to build a similar or competitive service or
            application;
            <br><br>
            b) Wexprez does not allow you to modify, translate, adapt, merge, make derivative works of, disassemble,
            decompile, reverse compile or reverse engineer any part of Apps,
            except to the extent the foregoing restrictions are expressly prohibited by applicable law;
            <br><br>
            c) You shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise
            commercially exploit any App in future;
            <br><br>
            d) Except as expressly stated herein, no part of any App may be copied, reproduced, distributed,
            republished, downloaded, displayed, posted or transmitted in any form or by any means, or
            <br><br>
            e) You shall not remove or destroy any copyright notices or other proprietary markings contained on or
            in
            any App. Any future release, update, or other addition to functionality of any App shall be subject to
            the
            terms of this Agreement, unless otherwise provided in terms associated with such addition.
            All copyright and other proprietary notices on any App content must be retained on any copies.
            <br><br>
            <b>Modification</b><br>
            Wexprez reserves the right, at any time, to modify, suspend, or discontinue the Apps or any part
            thereof with or without notice. You agree that Wexprez will not be liable to you or to any third
            party for any modification, suspension, or discontinuance of any App or any part thereof.

            <br><br>
            <b>Ownership</b><br>
            Apps provided to Users are licensed to users and not sold. Wexprez (and its licensors, where
            applicable) own all right, title and interest, including all related intellectual property rights,
            in and to all Apps. This Agreement is not a sale and does not convey to User any rights of ownership
            in or related to any App. The Wexprez name, logo, and the product names associated with the Apps
            belong Wexprez (or its licensors, where applicable), and no right or license is granted to use them.
            Wexprez (and its licensors, where applicable) reserve all rights not granted in this Agreement.
            <br><br>

            <b>Advertisement</b><br>
            When a User start or stop an App, it may display an ad (banner and/or interstitial or rewarded ads)
            may be displayed.
            <br><br>

            <b>Local Laws</b><br>
            Users are solely responsible for compliance with all applicable laws, including without limitation
            export and import regulations.
        </p>
        <br>

        <h5 class="text-center fw-bold">Safety Measures</h5>
        <b>User Generated Content</b><br>
        <p>User Generated Content (UGC) means all content uploads, distributes, or otherwise provides via App
            generated by a user. User is solely responsible for User Generated Content (UGC).
            <br>
            Any User Generated Content (UGC) you create is your property and you represent and warrant that:
            <br>
            <br>
            a. You have not made the User Generated Content (UGC) to be deliberately offensive, including (but not
            limited to) contents such as nudity, pornography, profanity, etc., and the User Generated Content (UGC)
            is not defamatory and does not infringe any applicable laws.
            <br><br>
            b. The content may be shared, so you grant Wexprez an irrevocable, worldwide, non-exclusive,
            royalty-free license to use, reproduce, distribute, modify, adapt, publish, translate, prepare
            derivative works of and display the User Generated Content (UGC) and you waive any and all moral or
            similar rights you may have over the User Generated Content (UGC).
            <br><br>
            c. You will indemnify and hold harmless Wexprez for all damages, costs and expenses incurred for
            breaching theses warranties.
            <br><br>
            User assumes all risks associated with use of User Generated Content (UGC), including any reliance on
            its accuracy, completeness or usefulness by others, or any disclosure of User Generated Content (UGC)
            that makes any third party personally identifiable. Users hereby represent and warrant that User
            Generated Content (UGC) does not violate the Acceptable User Policy (defined below). You may not state
            or imply that User Generated Content (UGC) is in any way provided, sponsored or endorsed by Wexprez.
            Wexprez is not obligated to backup any User Generated Content (UGC) and User Generated Content (UGC) may
            be deleted at any time. If a User wish they can, solely responsible for creating backup copies of their
            User Generated Content (UGC) if they desire.
            <br><br>
            Wexprez provides you an opportunity to upload and display content on the platform but declare & reserve
            the right that there will be no tolerance for objectionable content or abusive users and reserved the
            right to filter and/or flag and/or block objectionable content and abusive user.
            <br>
            Also able to remove the content and ejecting the user who provided the offending content within 24 hours
            (if any objectionable content reports).

            <br><br>
            <b>License</b><br>
            By uploading, distributing, or otherwise using your User Content with any App, you automatically grant,
            and you represent and warrant that you have the right to grant, to Wexprez an irrevocable, nonexclusive,
            royalty-free and fully paid, worldwide license, with the right to grant sublicenses, to reproduce,
            distribute, publicly display, publicly perform, prepare derivative works of, incorporate into other
            works, and otherwise use your User Content, solely to display your User Content on any App.

            <br><br>
            <b>Feedback</b><br>
            If you provide Wexprez any feedback or suggestions (as “Feedback”), you hereby assign to Wexprez all
            rights in the Feedback and agree that Wexprez shall have the right to use such Feedback and related
            information in any manner it deems appropriate. Any Feedback you provide to Wexprez will be treated as
            non-confidential and non-proprietary. You also agree that you will not submit to Wexprez any information
            or ideas that you consider to be confidential or proprietary.
            <br>
        </p><br>

        <h5 class="text-center fw-bold">Acceptable Use Policy</h5>
        <p>The following highlights Wexprez ‘s “Acceptable Use Policy”:
            <ul>
                <li>You agree not to use any App to upload, distribute, or otherwise use any User Content (a) which
                    violates any third-party right, including any copyright, trademark, patent, trade secret, moral
                    right, privacy right, right of publicity, or any other intellectual property or proprietary right;
                    (b) which is tortuous, trade libelous, defamatory, false, or intentionally misleading, (c) which is
                    harassing, abusive, threatening, harmful, vulgar, obscene, or offensive, or that contains
                    pornography, nudity, or graphic or gratuitous violence, or that promotes violence, racism,
                    discrimination, bigotry, hatred, or physical harm of any kind against any group or individual, or is
                    otherwise objectionable, (d) which is harmful to minors in any way; (e) which constitutes
                    unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters,
                    pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or
                    otherwise; or (f) which violates of any law, regulation, or contractual obligations.</li>
                <li>User agrees not to use any App to: (a) upload or distribute any computer viruses, worms, malicious
                    code, or any software intended to damage or alter a computer system or data; (b) collect information
                    or data regarding other users, including e-mail addresses, without their consent (e.g., using
                    harvesting bots, robots, spiders, or scrapers); (c) disable, overly burden, impair, or otherwise
                    interfere with servers or networks connected to Apps (e.g., a denial of service attack); (d) attempt
                    to gain unauthorized access to the Site or App or servers or networks connected to Apps (e.g.,
                    through password mining); or (e) interfere with another user’s use and enjoyment of any App.</li>
            </ul>

            <br>
            <b>Enforcement</b><br>
            Wexprez reserves the right to review any User Generated Content in our sole discretion. Wexprez may remove
            or modify User Generated Content at any time for any reason in our sole discretion with or without notice to
            you.

            <br><br>
            <b>Term and Termination</b><br>
            This Agreement commences on the date you accept this Agreement and will remain in full force and effect
            while you use the App, unless earlier terminated in accordance with this Agreement.
            <br>
            If you used any App prior to the date you accepted this Agreement, you hereby acknowledge and agree that
            this Agreement commences on the date you first use any App (whichever is earlier and which may be prior to
            the Agreement Version Date) and will remain in full force and effect while you use any App, unless earlier
            terminated in accordance with this Agreement.
            <br>
            Wexprez may (a) suspend your rights to use any App, and/or any related services or (b) terminate this
            Agreement, at any time for any reason at our sole discretion with or without notice to you, including if we
            in good faith believe you have violated the Acceptable Use Policy or any other provision of this Agreement.
            Wexprez reserves the right to terminate its Agreement with any user who repeatedly infringes third party
            copyright rights upon prompt notification to Wexprez by the copyright owner or the copyright owner’s legal
            agent.
            <br>
            Upon termination of this Agreement, your right to use the App will automatically terminate immediately. You
            understand that any termination may involve deletion of your User Content associated therewith from our live
            databases. Wexprez will not have any liability whatsoever to you for any termination of this Agreement,
            including deletion of your User Content. Even after this Agreement is terminated, the provisions of this
            Agreement will remain in effect.
            <br><br>

            <b>Indemnity</b><br>
            Users agree to defend, indemnify and hold harmless Wexprez (and its suppliers) from and against any claims,
            suits, losses, damages, liabilities, costs, and expenses (including reasonable attorneys’ fees) brought by
            third parties resulting from or relating to: (i) your use of any App, (ii) your User Content, or (iii) your
            violation of this Agreement. Wexprez reserves the right, at your expense, to assume the exclusive defense
            and control of any matter for which you are required to indemnify Wexprez and you agree to cooperate with
            our defense of these claims. You agree not to settle any matter without the prior written consent of
            Wexprez. Wexprez will use reasonable efforts to notify you of any such claim, action or proceeding upon
            becoming aware of it.
            <br><br>

            <b>Third Parties</b><br>
            <b>Application Stores</b><br>
            You acknowledge and agree that the availability of the App is dependent on the third party from which you
            received the App, e.g., the Apple iPhone or Android stores (“Application Store”). You acknowledge that this
            Agreement is between User and Wexprez and not with the Application Store. The Application Store is not
            responsible for the App, the content thereof, maintenance, support services, and warranty therefor, and
            addressing any claims relating to product liability, legal compliance, or intellectual property
            infringement. You agree to pay all fees charged by the Application Store in connection with App (if any).
            You agree to comply with, and your license to use App is conditioned upon your compliance with, all
            applicable third party terms of agreement (e.g., the Application Store’s terms and policies) when using App.
            You acknowledge that the Application Store (and its subsidiaries) are third party beneficiaries of this
            Agreement and will have the right to enforce this Agreement.

            <br><br>

            <b>Third Party Services</b><br>
            Wexprez may permit certain third party applications (like, ad networks) to provide content through the App.
            The App may be used to send content provided by the Third Party Service between users who have the Third
            Party Service installed on their device. When you do so, Wexprez will share information with the Third Party
            Service as described in the Wexprez Privacy Policy. Wexprez is not responsible for and does not control
            Third Party Services. Wexprez provides these Third Party Services only as a convenience to you as User.
            Wexprez has no obligation to review or monitor, and does not approve, endorse, or make any representations
            or warranties with respect to Third Party Services. User will use all Third Party Services at their own
            risk. When you access a Third Party Service, the applicable third party’s terms and policies apply,
            including the third party’s privacy policies. You should make whatever investigation you feel necessary or
            appropriate before proceeding with any transaction in connection with any Third Party Services.
            <br><br>

            <b>Other Users</b><br>
            An App may contain User Content provided by other users of the App. Wexprez is not responsible for and does
            not control User Content. Wexprez has no obligation to review or monitor, and does not approve, endorse, or
            make any representations or warranties with respect to User Content. User will use all Content and interact
            with other users at their own risk. Your interactions with other users are solely between you and the other
            user and we are under no obligation to become involved. You agree that Wexprez will not be responsible for
            any liability incurred as the result of any such interactions.


        </p>


    </div>
</section>
@endsection
